### ISSUE TITLE
Could not load type IResponseBodyPipeFeature

### ISSUE THREAD

**Issue by ehsan-mohammadi** [davidfowl/BombRMan#4]
I tried to run the game, using `dotnet run` and the game started successfully:

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: ...\BombRMan.Core
```

 But when I try to open `http://localhost:5000`, the browser doesn't show me anything and also I give this error in my vscode console:

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HLRGBC5832S3.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Features.IResponseBodyPipeFeature' from assembly 'Microsoft.AspNetCore.Http.Features, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)    
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)    
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1.OnConnectionAsync(ConnectionContext connectionContext)    
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher.Execute(KestrelConnection connection)
```

I found out, `IResponseBodyPipeFeature` doesn't exist in `Microsoft.AspNetCore.Http.Features`.
So, how can I solve it? Is there anything that I forgot to do?

**Comment by davidfowl** [comment]
What version are you running, 3.0?

**Comment by ehsan-mohammadi** [comment]
@davidfowl The version of `Microsoft.AspNetCore.Http.Features` is `3.0.0.0` and the version of `dotnet core` is `3.0.100-preview7-012821`. Also, the `TargetFramework` version is `3.0`.
I'm not sure but I think forgot to install some libraries. After I clone the project, should I need to add or update any library on my system?

**Comment by davidfowl** [comment]
Install the final version of .NET Core 3.0. What do you have installed?

**Comment by ehsan-mohammadi** [comment]
@davidfowl Many thanks for helping me! I updated my .NET Core to the latest version and the problem solved!
